#!/bin/sh

ADDON_NAME=hausbusdeip
RC_DIR=/usr/local/etc/config/rc.d
WWW_DIR=/usr/local/etc/config/addons/www/$ADDON_NAME
ADDON_DIR=/usr/local/etc/config/addons/$ADDON_NAME

mount -o remount,rw /

echo $1 >> /hausbus.txt

# Startscript anlegen
cp -af rc.d/$ADDON_NAME ${RC_DIR}/
chmod +x ${RC_DIR}/$ADDON_NAME

cp addon/S60HausBusDeInterface /etc/init.d/
chmod +x /etc/init.d/S60HausBusDeInterface
#rm /etc/init.d/S60HausBusDeInterface

# Web-Konfiguration anlegen
mkdir -p ${WWW_DIR}
cp -af www/* ${WWW_DIR}
chmod 755 ${WWW_DIR}

# Addon-Verzeichnis anlegen
mkdir -p ${ADDON_DIR}
cp -af addon/* ${ADDON_DIR}
chmod 755 ${ADDON_DIR}

# Nun alle Addon datein platformspezifisch kopieren
if [ "$1" = "noop" ]; then
  touch /hausbus.txt
elif [ "$1" = "" ]; then
  cp -af ccu1/* ${ADDON_DIR}/
elif [ "$1" = "CCU2" ]; then
  cp -af ccu2/* ${ADDON_DIR}/
elif [ "$1" = "CCU3" ]; then
  cp -af ccu3/* ${ADDON_DIR}/
elif [ "$1" == "HM-RASPBERRYMATIC" ]; then
  cp -af ccurm/* ${ADDON_DIR}/
else 
  cp -af ccu3/* ${ADDON_DIR}/
fi

cp -raf hausbusdeinterface/* ${ADDON_DIR}/

# Add menu entry
cp -af addon/update_hm_addons.tcl ${ADDON_DIR}/
${ADDON_DIR}/update_hm_addons.tcl -a ${ADDON_NAME} -name "Haus-Bus.de<br>Komponenten" -url /addons/${ADDON_NAME} -de "<li>Haus-Bus.de<br>Smarthome Komponenten</li>" -en "<li>Haus-Bus.de<br>Smarthome Components</li>"

#touch /usr/local/etc/config/hm_addons.cfg
#/usr/local/etc/config/addons/hausbusdeip/update_addon hausbusdeip /usr/local/etc/config/addons/hausbusdeip/hm_hausbusde-addon.cfg

# Symbolic Links
rm -f ${WWW_DIR}/VERSION.txt
ln -sf ${ADDON_DIR}/VERSION ${WWW_DIR}/VERSION.txt
rm -f ${WWW_DIR}/addon
ln -sf ${ADDON_DIR} ${WWW_DIR}/addon


# sync filesystem to make sure all changes are written to disk
sync